name: servicetoservicedemo
version: 0.1.1.0
summary: servicetoservicedemo
description: 'simple demo'

base: core22
confinement: strict
grade: stable

# Limit architectures as ppcel64 doesn't build currently
architectures:
  - build-on: amd64
  - build-on: arm64


apps:
  run:
    command: bin/launcher.wrapper
    daemon: simple
    plugs:
      - network-bind
      - network-status
      - network-observe
      - serial-port
      - datalayer
    environment:
       "LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/python3/dist-packages"
      

    
  desktop-launch:
    command: bin/desktop-launch
    plugs:
      - desktop  

parts:


  requests:
    plugin: python
    build-environment:
      - PYTHONPATH: "$SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages"

    stage-packages:
      - wget
      - libssl-dev
      - libcurl4-openssl-dev
      - libcurl-dev
      - curl

      
    python-packages:
      - requests     # just this is needed for licensing
      - flask        # just for app.py
      - werkzeug     # just for app.py
      - jwcrypto     # just for app.py
      - six          # optional..
      - autopep8


    build-packages:
      - python3-dev
      - python3-wheel
      - build-essential
      - python3-setuptools

     
 
 
  shscripts:  
    source: ./shscripts/
    plugin: dump
    organize:
      '*': bin/
      

  configs:
    source: ./configs
    plugin: dump
    organize:
      'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/
      'secure-assets/*': secure-assets/${SNAPCRAFT_PROJECT_NAME}/



plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 

  licensing-service:
    interface: content
    content: licensing-service
    target: $SNAP_DATA/licensing-service
slots:
  secure-assets:
    interface: content
    content: secure-assets
    source:
      read:
        - $SNAP/secure-assets/${SNAPCRAFT_PROJECT_NAME}

  service-token:
    interface: content
    content: service-token
    source:
      write:
        - $SNAP_DATA/service-token/${SNAPCRAFT_PROJECT_NAME}

  package-assets:
    interface: content
    content: package-assets
    source:
      read:
        - $SNAP/package-assets/${SNAPCRAFT_PROJECT_NAME}